// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'src/tokens/colors';
import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';

const HeadingCss = `
  color: ${colors.deepBlue};
  font-size: ${fontSizes.heading};
  font-family: ${fontFamilies.roboto};
  font-weight: ${fontWeights.bold};
  text-align: left;
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: 32px;
`;

export default HeadingCss;