// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'src/tokens/colors';

const FormCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: 320px;
  background-color: ${colors.white};
  box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.4);
`;

export default FormCss;