// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'src/tokens/spacing';
import colors from 'src/tokens/colors';
import radii from 'src/tokens/radii';
import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';

const ButtonCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  padding-left: ${spacing.small};
  padding-right: ${spacing.small};
  height: ${spacing.tall};
  border-radius: ${radii.rounded};
  color: ${colors.pureWhite};
  font-size: ${fontSizes.regular};
  font-family: ${fontFamilies.roboto};
  font-weight: ${fontWeights.bold};
  text-align: center;

  &.normal {
    background-color: ${colors.purple};
  }

  &:hover {
    background-color: ${colors.deepBlue};
  }

`;

export default ButtonCss;