// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';
import spacing from 'src/tokens/spacing';

const FooterCss = `
  color: rgba(0, 0, 0, 1);
  font-size: ${fontSizes.regular};
  font-family: ${fontFamilies.roboto};
  font-weight: ${fontWeights.standard};
  text-align: center;
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: ${spacing.spacious};
`;

export default FooterCss;