// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'src/tokens/colors';

const ImageCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  object-fit: cover;
  height: 296px;
  background-color: ${colors.black};
`;

export default ImageCss;