// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const colors = {
 "pureWhite": "rgba(255, 255, 255, 1)",
 "white": "rgba(249, 246, 246, 1)",
 "gray": "rgba(89, 89, 89, 1)",
 "purple": "rgba(85, 33, 232, 1)",
 "deepBlue": "rgba(20, 6, 62, 1)",
 "black": "rgba(27, 25, 25, 1)"
}

module.exports = colors;