// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const fontSizes = {
 "small": "1rem",
 "regular": "1.25rem",
 "heading": "2rem"
}

module.exports = fontSizes;