// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

const spacing = {
 "tiny": "0.25rem",
 "small": "0.5rem",
 "big": "1rem",
 "spacious": "1.5rem",
 "tall": "3rem"
}

module.exports = spacing;