// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import spacing from 'src/tokens/spacing';
import colors from 'src/tokens/colors';
import radii from 'src/tokens/radii';
import fontSizes from 'src/tokens/fontSizes';
import fontFamilies from 'src/tokens/fontFamilies';
import fontWeights from 'src/tokens/fontWeights';

const InputCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  padding-left: ${spacing.small};
  padding-right: ${spacing.small};
  height: ${spacing.tall};
  background-color: ${colors.pureWhite};
  border-color: ${colors.gray};
  border-radius: ${radii.rounded};
  font-size: ${fontSizes.regular};
  font-family: ${fontFamilies.roboto};
  font-weight: ${fontWeights.standard};
  text-align: left;

  &.normal {
    color: ${colors.black};
  }

  &:invalid {
    color: rgba(222, 23, 23, 1);
  }

`;

export default InputCss;