// THIS FILE IS AUTO-GENERATED BY FIGMAGIC. DO NOT MAKE EDITS IN THIS FILE! CHANGES WILL GET OVER-WRITTEN BY ANY FURTHER PROCESSING.

import colors from 'src/tokens/colors';
import radii from 'src/tokens/radii';
import shadows from 'src/tokens/shadows';

const CardCss = `
  width: 100%;
  box-sizing: border-box;
  border: 0;
  border-style: solid;
  height: 488px;
  background-color: ${colors.pureWhite};
  border-radius: ${radii.rounded};
  box-shadow: ${shadows.sharp};
`;

export default CardCss;